name: Lint

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  lint:
    name: Check lint code with Black
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Setup Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install Black
        run: pip3 install black

      - name: Check lint
        run: black --check scraper
